/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ViewLibraryImport } from './routes/view-library'
import { Route as ViewConfigImport } from './routes/view-config'
import { Route as ViewImport } from './routes/view'
import { Route as TimeframeImport } from './routes/timeframe'
import { Route as TephigramImport } from './routes/tephigram'
import { Route as RollImport } from './routes/roll'
import { Route as PlotImport } from './routes/plot'
import { Route as MapImport } from './routes/map'
import { Route as FlightSummaryImport } from './routes/flight-summary'
import { Route as DashImport } from './routes/dash'
import { Route as ChatImport } from './routes/chat'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const PlotOptionsLazyImport = createFileRoute('/plot-options')()

// Create/Update Routes

const PlotOptionsLazyRoute = PlotOptionsLazyImport.update({
  path: '/plot-options',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/plot-options.lazy').then((d) => d.Route))

const ViewLibraryRoute = ViewLibraryImport.update({
  path: '/view-library',
  getParentRoute: () => rootRoute,
} as any)

const ViewConfigRoute = ViewConfigImport.update({
  path: '/view-config',
  getParentRoute: () => rootRoute,
} as any)

const ViewRoute = ViewImport.update({
  path: '/view',
  getParentRoute: () => rootRoute,
} as any)

const TimeframeRoute = TimeframeImport.update({
  path: '/timeframe',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/timeframe.lazy').then((d) => d.Route))

const TephigramRoute = TephigramImport.update({
  path: '/tephigram',
  getParentRoute: () => rootRoute,
} as any)

const RollRoute = RollImport.update({
  path: '/roll',
  getParentRoute: () => rootRoute,
} as any)

const PlotRoute = PlotImport.update({
  path: '/plot',
  getParentRoute: () => rootRoute,
} as any)

const MapRoute = MapImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))

const FlightSummaryRoute = FlightSummaryImport.update({
  path: '/flight-summary',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/flight-summary.lazy').then((d) => d.Route),
)

const DashRoute = DashImport.update({
  path: '/dash',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashImport
      parentRoute: typeof rootRoute
    }
    '/flight-summary': {
      id: '/flight-summary'
      path: '/flight-summary'
      fullPath: '/flight-summary'
      preLoaderRoute: typeof FlightSummaryImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/plot': {
      id: '/plot'
      path: '/plot'
      fullPath: '/plot'
      preLoaderRoute: typeof PlotImport
      parentRoute: typeof rootRoute
    }
    '/roll': {
      id: '/roll'
      path: '/roll'
      fullPath: '/roll'
      preLoaderRoute: typeof RollImport
      parentRoute: typeof rootRoute
    }
    '/tephigram': {
      id: '/tephigram'
      path: '/tephigram'
      fullPath: '/tephigram'
      preLoaderRoute: typeof TephigramImport
      parentRoute: typeof rootRoute
    }
    '/timeframe': {
      id: '/timeframe'
      path: '/timeframe'
      fullPath: '/timeframe'
      preLoaderRoute: typeof TimeframeImport
      parentRoute: typeof rootRoute
    }
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewImport
      parentRoute: typeof rootRoute
    }
    '/view-config': {
      id: '/view-config'
      path: '/view-config'
      fullPath: '/view-config'
      preLoaderRoute: typeof ViewConfigImport
      parentRoute: typeof rootRoute
    }
    '/view-library': {
      id: '/view-library'
      path: '/view-library'
      fullPath: '/view-library'
      preLoaderRoute: typeof ViewLibraryImport
      parentRoute: typeof rootRoute
    }
    '/plot-options': {
      id: '/plot-options'
      path: '/plot-options'
      fullPath: '/plot-options'
      preLoaderRoute: typeof PlotOptionsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ChatRoute,
  DashRoute,
  FlightSummaryRoute,
  MapRoute,
  PlotRoute,
  RollRoute,
  TephigramRoute,
  TimeframeRoute,
  ViewRoute,
  ViewConfigRoute,
  ViewLibraryRoute,
  PlotOptionsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat",
        "/dash",
        "/flight-summary",
        "/map",
        "/plot",
        "/roll",
        "/tephigram",
        "/timeframe",
        "/view",
        "/view-config",
        "/view-library",
        "/plot-options"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/dash": {
      "filePath": "dash.tsx"
    },
    "/flight-summary": {
      "filePath": "flight-summary.tsx"
    },
    "/map": {
      "filePath": "map.tsx"
    },
    "/plot": {
      "filePath": "plot.tsx"
    },
    "/roll": {
      "filePath": "roll.tsx"
    },
    "/tephigram": {
      "filePath": "tephigram.tsx"
    },
    "/timeframe": {
      "filePath": "timeframe.tsx"
    },
    "/view": {
      "filePath": "view.tsx"
    },
    "/view-config": {
      "filePath": "view-config.tsx"
    },
    "/view-library": {
      "filePath": "view-library.tsx"
    },
    "/plot-options": {
      "filePath": "plot-options.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
